const partnerships = [
  { name: '해외 마케팅' },
  { name: '퍼블리셔' },
  { name: '캐드원(제도사)' },
  { name: '해외 세일즈' },
  { name: '해외 CS' },
  { name: '코딩' },
  { name: '프로그래밍' },
  { name: '소프트웨어' },
  { name: '하드웨어' },
  { name: '데이터베이스' },
  { name: '컴파일러' },
  { name: '디버깅' },
  { name: '알고리즘' },
  { name: '변수' },
  { name: '함수' },
  { name: '클래스' },
  { name: '객체' },
  { name: '인터페이스' },
  { name: '프레임워크' },
  { name: '오픈소스' },
  { name: '네트워크' },
  { name: '서버' },
  { name: '클라우드' },
  { name: '코드' },
  { name: '모듈' },
] as const;

export { partnerships };
